Validator Monitoring using Grafana added
zeta-chain/docs pull request #174
Opened 2023-10-09 16:23 UTC by vasylcode

2023-10-26 00:06 UTC, CharlieMc0 approved these changes

2023-10-26 00:07 UTC, CharlieMc0 requested changes
Besides the merge conflict this looks good. Thanks for the contribution. Once the conflict as been fixed we can approve and merge it in. 

We've replaced zetavisor so any reference to it should be `cosmovisor` instead.

2023-10-31 07:18 UTC, fadeev commented
@CharlieMc0 can you, please, review again? Thanks!

2023-11-06 08:55 UTC, fadeev approved these changes

2023-11-09 06:54 UTC, fadeev commented
@CharlieMc0 please, review changes so we can merge.

2023-11-13 17:06 UTC, CharlieMc0 approved these changes

2023-11-14 08:45 UTC, merged