remove zetavisor and replace with cosmovisor
zeta-chain/docs pull request #175
Opened 2023-10-13 20:44 UTC by billyyang423

2023-10-15 05:33 UTC, fadeev approved these changes

2023-10-15 19:36 UTC, CharlieMc0 requested changes
`cosmovisor` should be lowercase when it's a directory or a command

Make sure `DAEMON_ALLOW_DOWNLOAD_BINARIES=false` in the examples. 

Delete this whole section `https://www.zetachain.com/docs/validators/setting-up-zetavisor/#zetavisor-environment-variables`

2023-10-15 19:36 UTC, CharlieMc0 commented on docs/validators/cosmovisor.mdx
> +ExecStart=Cosmovisor start --home /home/zetachain/.zetacored/ --log_format json  --moniker <YOUR_NODE_NAME_HERE>
Should be lower case `cosmosvisor`

2023-10-15 19:37 UTC, CharlieMc0 commented on docs/validators/cosmovisor.mdx
> +links and place it in the `Cosmovisor/genesis/bin/` directory. This example
Should be lower case cosmosvisor

2023-10-15 19:37 UTC, CharlieMc0 commented on docs/validators/cosmovisor.mdx
> +chmod +x ~/.zetacored/Cosmovisor/genesis/bin/zetacored
Should be lower case cosmosvisor

2023-10-15 19:38 UTC, CharlieMc0 commented on docs/validators/cosmovisor.mdx
>      associated with each binary (e.g. $HOME/.zetacored, etc.).
Delete this whole section and replace it with 

## More Information About Cosmovisor 
For more detailed information about Cosmosvisor you can visit the [Cosmos Documentation Here](https://docs.cosmos.network/main/build/tooling/cosmovisor)

2023-10-16 19:18 UTC, CharlieMc0 commented on docs/validators/cosmovisor.mdx
> +wget https://zetachain-external-files.s3.amazonaws.com/binaries/athens3/latest/zetacored-ubuntu-22-amd64
Replace this link with https://github.com/zeta-chain/node/releases/download/latest/zetacored-ubuntu-22-amd64

2023-10-16 19:18 UTC, CharlieMc0 commented on docs/validators/cosmovisor.mdx
> +### Setup `Cosmovisor` systemd service
Cosmosvisor should be lower case if it's written as `code` inside ``

2023-10-16 19:50 UTC, CharlieMc0 approved these changes

2023-10-16 20:42 UTC, CharlieMc0 approved these changes

2023-10-16 20:43 UTC, CharlieMc0 approved these changes

2023-10-16 20:53 UTC, merged